welcome-to-sharesphere = Welcome to ShareSphere!
markdown-help-1 = To add formatting to your content, the 'Markdown' mode must be activated with the following button:{ " " }
markdown-help-2 = When the 'Markdown' mode is activated, your input will be parsed using{ " " }
markdown-help-3 =
     (with the addition of 'Spoilers') and a preview of your content will be displayed.
    Quick-format buttons are also available so that you don't need to remember the GFM syntax!
    Finally, 'Spoiler' formatting can be generated by adding '||' on both side of your text or
    by selecting it and using the 'Spoiler' quick format button:{ " " }

invalid-link = Invalid link
invalid-domain-name = Invalid domain name
invalid-video-format = Your browser doesn't support this video's format.

not-authenticated-message = Please authenticate yourself.
authentication-failed-message = Sorry, we had some trouble authenticating you.
internal-error-message = Something went wrong.
not-authorized-message = You're in a restricted area, please do not resist.
sphere-ban-until-message = You are banned from this sphere until
permanent-sphere-ban-message = You are permanently banned from this sphere.
global-ban-until-message = You are banned from ShareSphere until
permanent-global-ban-message = You are permanently banned from ShareSphere.
bad-request-message = Sorry, we didn't understand your request.
unavailable-message = Sorry, we've got noise on the line.
not-found-message = There's nothing here.
payload-too-large-message = Payload exceeds the  { $byte_limit } Bytes limit.

clipboard-error-message = Clipboard API not supported in your browser.
copy-link-to-clipboard-message = Copied link to clipboard.

refresh = Refresh
cancel = Cancel
submit = Submit

sphere-banner = Sphere banner