refresh = Refresh
cancel = Cancel
submit = Submit
create = Create
assign = Assign
login = Login
search = Search
manage = Manage
new = New
join = Join
close = Close

username = Username
role = Role

sphere-banner = Sphere banner
sphere-icon = Sphere icon
sphere-description = Sphere description
satellites = Satellites
sphere-categories = Sphere categories
categories = Categories
moderators = Moderators
rules = Rules
image-preview = Image Preview

number-short = N°
title = Title
name = Name
content = Content
description = Description
category = Category
pinned = Pinned
active = Active
spoiler = Spoiler
nsfw-content = NSFW content
color = Color

filters = Filters
category-filters = Category filters
all = All
only-categories = Only categories

infringed-rule = Infringed rule
moderator-message = Moderator message
banned-users = Banner users

link = Link
link-none = None
link-link = Link
link-embed = Embed
link-url = Url

home = Home
subscribed = Subscribed
popular = Popular
navigate-sphere = Navigate to Sphere {$sphere_name}

hot = Hot
trending = Trending
best = Best
recent = Recent

create-sphere = Settle a Sphere!
create-satellite = Create a Satellite
edit-satellite = Edit Satellite
load-replies = Load replies
share-comment = Share a comment
your-comment = Your comment...
delete-comment = Delete comment

welcome-to-sharesphere = Welcome to ShareSphere!
sharesphere-right-sidebar-1 =
    ShareSphere is the place to exchange with other people about
    your hobbies, news, art, jokes and many more topics.
sharesphere-right-sidebar-2 =
    ShareSphere is a non-profit, add-free, open source website
    with a focus on transparency, privacy and community empowerment.
    You can find more information on the website and its rules below.
about-sharesphere = About ShareSphere
terms-and-conditions = Terms and Conditions
privacy-policy = Privacy Policy
content-policy = Content Policy
sphere-cockpit = Sphere Cockpit
single-comment-tree = Single comment tree view. Back to post.

until = Until
permanent = Permanent

time-seconds-short = s
time-minutes-short = m
time-hours-short = h
time-days-short = d
time-months-short = mo
time-years-short = y

time-seconds = {$count ->
    [one] {$count} second
    *[other] {$count} seconds
}
time-minutes = {$count ->
   [one] {$count} minute
   *[other] {$count} minutes
}
time-hours = {$count ->
   [one] {$count} hour
   *[other] {$count} hours
}
time-days = {$count ->
   [one] {$count} day
   *[other] {$count} days
}
time-months = {$count ->
   [one] {$count} month
   *[other] {$count} months
}
time-years = {$count ->
   [one] {$count} year
   *[other] {$count} years
}

markdown-help-1 = To add formatting to your content, the 'Markdown' mode must be activated with the following button:{" "}
markdown-help-2 = When the 'Markdown' mode is activated, your input will be parsed using{" "}
markdown-help-3 =
     (with the addition of 'Spoilers') and a preview of your content will be displayed.
    Quick-format buttons are also available so that you don't need to remember the GFM syntax!
    Finally, 'Spoiler' formatting can be generated by adding '||' on both side of your text or
    by selecting it and using the 'Spoiler' quick format button:{" "}

invalid-link = Invalid link
invalid-domain-name = Invalid domain name
invalid-video-format = Your browser doesn't support this video's format.
copy-link-to-clipboard-message = Copied link to clipboard.
clipboard-error-message = Clipboard API not supported in your browser.

delete-warning = This cannot be undone.
unavailable = Unavailable

not-authenticated-message = Please authenticate yourself.
authentication-failed-message = Sorry, we had some trouble authenticating you.
internal-error-message = Something went wrong.
not-authorized-message = You're in a restricted area, please do not resist.
sphere-ban-until-message = You are banned from this sphere until
permanent-sphere-ban-message = You are permanently banned from this sphere.
global-ban-until-message = You are banned from ShareSphere until
permanent-global-ban-message = You are permanently banned from ShareSphere.
bad-request-message = Sorry, we didn't understand your request.
unavailable-message = Sorry, we've got noise on the line.
not-found-message = There's nothing here.
payload-too-large-message = Payload exceeds the  {$byte_limit} Bytes limit.